apiVersion: v1
kind: Service
metadata:
    name: "myk801-b3fe"
    labels:
        app: "myk801-b3fe"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "myk801-b3fe"