on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: azurecontaineren01.azurecr.io
        username: ${{ secrets.acr_azurecontaineren01_username }}
        password: ${{ secrets.acr_azurecontaineren01_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t azurecontaineren01.azurecr.io/myk801:${{ github.sha }}
        docker push azurecontaineren01.azurecr.io/myk801:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myk801_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep mynodeapps-azure | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace mynodeapps-azure`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: mynodeapps-azure
        container-registry-url: azurecontaineren01.azurecr.io
        container-registry-username: ${{ secrets.acr_azurecontaineren01_username }}
        container-registry-password: ${{ secrets.acr_azurecontaineren01_password }}
        secret-name: myk801dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: mynodeapps-azure
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          azurecontaineren01.azurecr.io/myk801:${{ github.sha }}
        imagepullsecrets: |
          myk801dockerauth